### PR TITLE
implement reduce, with optional start value

### PR DESCRIPTION
**Pull request by Solaxun**
Had a go at implementing reduce.  

It would be easy to handle without an optional starting accumulator, but in the spirit of fully replicating the built-in version I decided to build that functionality out.  There is quite a bit of overhead for having that convenience though (in the form of additional if branching , duplicated calling logic in function_reduce etc.), so I'll leave it to @osantana to decide what's best.  

This can be simplified if we do not care about the optional accumulator, but the issue requested full replication so that's what I've done.

### CODE REVIEW

**Comment by osantana** [comment]
Please, can you update this implementation after #26 rewrite/refactoring?

**Comment by Solaxun** [comment]
@osantana  Sure I can take a look - let me know first though if #23 plans to have a go at it, since it looks like we both might be working on the same thing.  If not, I'll try to revise to match your refactoring.

**Comment by osantana** [comment]
Would you like to talk with the #23 author? Both implementations look similar.

**Comment by Solaxun** [comment]
The main difference was that I allowed for an optional start value, similar to the built-in version.  I don't think the other submission did this.  I'll try to get in touch with the other author.

**Comment by osantana** [comment]
> The main difference was that I allowed for an optional start value, similar to the built-in version. I don't think the other submission did this. I'll try to get in touch with the other author.

Yes. You are right. I think your implementation is more complete, so, if you refactor it I can merge (then I just close #23).

**Pull request closed without merging**
