### PR TITLE
implement =map expression parsing

### PR DESCRIPTION
**Pull request by Solaxun**
An attempt at issue #2, with an additional test.

### CODE REVIEW

**Comment by dasdachs** [comment]
@Solaxun will you implement reduce in the same way?

**Comment by Solaxun** [comment]
Probably similar if the maintainer is OK with it.  I might do some cleanup
but the overall idea will be similar.

**Comment by osantana** [comment]
I really liked the syntax for functions with arguments. And I'll probably merge this PR as-is. But I'd like to ask permission to propose some improvements in implementation in a future PR.

**Comment by Solaxun** [comment]
Absolutely.... I'm all for suggestions!

**Pull request merged**
