### PR TITLE
Added Pipenv support and added .venv to .gitignore

### PR DESCRIPTION
**Pull request by dasdachs**

### CODE REVIEW

**Review by osantana — CHANGES_REQUESTED** [review]
Please, remove requirements*.txt to avoid duplication.

**Comment by dasdachs** [comment]
@osantana will do? Can I update the README.md and add installaton instructions

**Comment by osantana** [comment]
> Can I update the README.md and add installaton instructions

Yes. Sure! :)

**Comment by osantana** [comment]
I think we need to update .travis.yml to use pipenv instead of requirements.txt :)

**Review by osantana — APPROVED** [review]

**Pull request merged**
